#http_path_prefix: /MatMedV2_CRM

public_urls:
    - /api/public
    - /firewall/message
    - '~^\/share(?=\\/|$)~ui'

# Подключаемые бандлы
required_bundles:
    firewall: Firewall_Bundle
    users:    Users_Bundle
    main:     Main_Bundle

#бандл главной страницы (bundle/IndexController->indexAction())
main_page_bundle: main

#Назначаем отображение определенных страниц на коды Ответов
# Если будет Ответ содержит код, не прописанный ниже или страницы не существует, 
# вернется стандартный Response  с кодом
system_responses:
    401: /share/firewall/authorize
    403: /share/firewall/accessdenied
    404: /firewall/message/notfound